version: "3.7"

services:
  lbtest:
    build: .
    command: node index.js
    ports:
      - "7777:2222"
    volumes:
      - nfs-volume:/home/app/files

volumes:
  nfs-volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=35.224.170.61,rw
      device: :/var/nfs/general
