version: "3.7"

services:
  lbtest:
    build: .
    command: node index.js
    ports:
      - "7777:2222"
    volumes:
      - nfs-volume1:/home/app/files

volumes:
  nfs-volume1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,rw
      device: :/var/nfs/general
